# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('min_qualification', models.CharField(max_length=100)),
                ('min_experience', models.CharField(max_length=100)),
                ('deadline_date', models.DateField()),
                ('score', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
