# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobonicjob', '0001_initial'),
        ('jobonicsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobonicEntity', '0003_entity_entity_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicEntity.Entity'),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Industry'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.JobStatus'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Profession'),
        ),
    ]
