# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicjob', '0002_auto_20170714_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
