# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobonicuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
