# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicusers', '0002_auto_20170629_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[(b'Admin', b'Administrator'), (b'Recruit', b'Recruiter'), (b'seeker', b'Job Seeker')], default=b'seeker', max_length=15)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('facebook', models.CharField(blank=True, max_length=30)),
                ('twitter', models.CharField(blank=True, max_length=30)),
                ('linkedIn', models.CharField(blank=True, max_length=30)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobonicuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='jobonicuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='jobonicuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='jobonicuser',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='jobonicuser',
            name='maiden_name',
        ),
        migrations.RemoveField(
            model_name='jobonicuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='jobonicuser',
            name='score',
        ),
        migrations.RemoveField(
            model_name='jobonicuser',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='jobonicuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
