# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicusers', '0005_auto_20170716_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobonicuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobonicEntity.Entity'),
        ),
    ]
