# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicusers', '0006_auto_20170716_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobonicuser',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobonicEntity.Entity'),
        ),
    ]
