# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobonicEntity', '0002_auto_20170710_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
