# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobonicEntity', '0003_entity_entity_admin'),
        ('jobonicsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicEntity.Entity'),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Industry'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.JobStatus'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Profession'),
        ),
        migrations.AddField(
            model_name='industry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitysize',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_sizes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applications',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Job'),
        ),
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.ApplicationStage'),
        ),
    ]
