# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicsapp', '0002_auto_20170714_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerlevel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
