# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicsapp', '0002_auto_20170629_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.URLField(),
        ),
    ]
