# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobonicsapp', '0003_auto_20170716_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstage',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='entitysize',
            name='size_info',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
